
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/utils/cmake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
...
